
// export const FETCH_REQUEST_PARAMETERS = "FETCH_REQUEST_PARAMETERS";
// export const TAB_CHANGE_HANDLER = "TAB_CHANGE_HANDLER";
// export const PDF_FINAL_BASE64 = "PDF_FINAL_BASE64";
// export const SET_INITIALHTML_XML = "SET_INITIALHTML_XML";
export const SET_LOGGEDIN_USER = "SET_LOGGEDIN_USER";


