
// export const FETCH_REQUEST_PARAMETERS = "FETCH_REQUEST_PARAMETERS";
// export const TAB_CHANGE_HANDLER = "TAB_CHANGE_HANDLER";
// export const PDF_FINAL_BASE64 = "PDF_FINAL_BASE64";
// export const SET_INITIALHTML_XML = "SET_INITIALHTML_XML";
export const SET_LOGGEDIN_USER = "SET_LOGGEDIN_USER";
export const SET_SHOW_FORM = "SET_SHOW_FORM";
export const SET_SHOW_ACCORDIAN = "SET_SHOW_ACCORDIAN";
export const SET_SHOW_ACCORDIAN2 = "SET_SHOW_ACCORDIAN2";
export const SET_DIRECTORACTIVE_POSTS="SET_DIRECTORACTIVE_POSTS";
export const SET_APPLICANTAPPLIED_POSTS="SET_APPLICANTAPPLIED_POSTS";
export const SET_APPLICANTACTIVE_POSTS="SET_APPLICANTACTIVE_POSTS";
export const SET_DIRECTORUPDATE_FORMID="SET_DIRECTORUPDATE_FORMID";
export const SET_APPLICANTUPDATE_FORMID="SET_APPLICANTUPDATE_FORMID";
export const SET_APPLICANT_FORMID="SET_APPLICANT_FORMID";
export const SET_LIST_LOADER="SET_LIST_LOADER";
export const FETCH_ACTIVE_ROLES="FETCH_ACTIVE_ROLES";
export const SET_LOGIN_DIRECTOR="SET_LOGIN_DIRECTOR";
export const SET_LOGIN_APPLICANT="SET_LOGIN_APPLICANT";
export const SET_MATCHED_CANDIDATES="SET_MATCHED_CANDIDATES";
export const GET_MATCHED_CANDIDATES="GET_MATCHED_CANDIDATES";
export const GET_CURRENT_ACCORDIANAPP_ID="GET_CURRENT_ACCORDIANAPP_ID";
export const GET_CURRENT_ACCORDIANAPP_ID2="GET_CURRENT_ACCORDIANAPP_ID2";
export const SET_PERCENTAGE="SET_PERCENTAGE";
export const SET_SHORTLISTED_CANDIDATES="SET_SHORTLISTED_CANDIDATES";
export const GET_SHORTLISTED_CANDIDATES="GET_SHORTLISTED_CANDIDATES";


export const DISPLAY_ERROR="DISPLAY_ERROR";
export const DISPLAY_SUCCESS="DISPLAY_SUCCESS";

// applicantAppliedPosts







